sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - django=django18 storage=redis
  - django=django18 storage=rdbms
  - django=django19 storage=redis
  - django=django19 storage=rdbms
services:
  - redis-server
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$django-$storage
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
