sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - django=django18
  - django=django19
services:
  - redis-server
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$django-rdbms -e py${TRAVIS_PYTHON_VERSION//[.]/}-$django-redis
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
